### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [50,32] vs. [100,32]

### ISSUE THREAD

**Issue by ghost** [NicGian/text-VAE#1]
`Hi` there,

I am getting an error like this when running with with my own data. I have a csv file containing 191 rows and just one column.Some portions of my data is like this
     

      text
0    He said the way my blue eyes shined \r\r\n Put...
1    State the obvious, I didn't get my perfect fan...
2    Drew looks at me \r\r\n I fake a smile so he w...
3    I don't know what I want \r\r\n So, don't ask ...
4    You have a way of coming easily to me \r\r\n A...
5    I didn't know \r\r\n What I would find \r\r\n ...
6    Seems the only one who doesn't see your beauty...
7    Cory's eyes are like a jungle \r\r\n He smiles...
8    It's strange to think \r\r\n The songs we used...
......
188  Turn WYCD on \r\r\n You're on your Grunwald \r...
189  Jesus, Jesus, precious is your name \r\r\n Whe...
190  You wanna dance you really wanna let it go \r\...

[191 rows x 1 columns]

Now the complete traceback is--

Total params: 677,413
Trainable params: 510,663
Non-trainable params: 166,750
__________________________________________________________________________________________________
-------epoch:  0 --------
Epoch 1/1
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.6\helpers\pydev\pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.6\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "I:/PycharmProjects/SDS_MLP/LINEARAXON_PRODUCTION_LEVEL_1/text2lyrics_test/test_taylor.py", line 215, in <module>
    validation_data=(data_1_val, data_1_val))
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 191, in fit_generator
    class_weight=class_weight)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1220, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2661, in __call__
    return self._call(inputs)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2631, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "C:\Users\aminp\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [50,32] vs. [100,32]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]

Now to point out the problem is in --

vae.fit_generator(sent_generator(TRAIN_DATA_FILE, batch_size / 2),
                      steps_per_epoch=n_steps, epochs=1, callbacks=[checkpointer],
                      validation_data=(data_1_val, data_1_val))

#in validation_data

what i change in the code is--replacement with yours is also shown in #(as comment)

1.with codecs.open(TRAIN_DATA_FILE, encoding='utf-8') as f:
    reader = csv.reader(f, delimiter=',')
    header = next(reader)
    for values in reader:
        texts.append(values[0])
        #texts.append(values[1])
print('Found %s texts in file.csv' % len(texts))

2.data_1_val = data_1[160:180] #as i have 191 rows

3.def sent_generator(TRAIN_DATA_FILE, chunksize):
    reader = pd.read_csv(TRAIN_DATA_FILE, chunksize=chunksize, iterator=True)
    for df in reader:
        # print(df.shape)
        # df=pd.read_csv(TRAIN_DATA_FILE, iterator=False)
        val3 = df.iloc[:, 0:1].values.tolist()
        #val4 = df.iloc[:, 1:2].values.tolist()
        flat3 = [item for sublist in val3 for item in sublist]
        #flat4 = [str(item) for sublist in val4 for item in sublist]
        texts = []
        texts.extend(flat3[:])
        #texts.extend(flat4[:])

        sequences = tokenizer.texts_to_sequences(texts)
        data_train = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
        yield [data_train, data_train]

4.nb_epoch=100
n_steps = (186/2)/batch_size #we use the first 800000, i use 186 here
for counter in range(nb_epoch):
    print('-------epoch: ', counter, '--------')
    vae.fit_generator(sent_generator(TRAIN_DATA_FILE, batch_size / 2),
                      steps_per_epoch=n_steps, epochs=1, callbacks=[checkpointer],
                      validation_data=(data_1_val, data_1_val))

Please i need help.I will be grateful if you can give the solution.

Thanks in Advance and keep up your great works.World needs guys like you to share those skills.

**Comment by ghost** [comment]
did you find solution

**Comment by ghost** [comment]
Train on 1476 samples, validate on 0 samples
Epoch 1/100
 100/1476 [=>............................] - ETA: 23s - loss: 179.8707 - kl_loss 200/1476 [===>..........................] - ETA: 12s - loss: 179.0795 - kl_loss 300/1476 [=====>........................] - ETA: 8s - loss: 178.2200 - kl_loss: 400/1476 [=======>......................] - ETA: 6s - loss: 177.2747 - kl_loss: 500/1476 [=========>....................] - ETA: 5s - loss: 175.7491 - kl_loss: 600/1476 [===========>..................] - ETA: 4s - loss: 172.9643 - kl_loss: 700/1476 [=============>................] - ETA: 3s - loss: 168.5350 - kl_loss: 800/1476 [===============>..............] - ETA: 3s - loss: 161.8723 - kl_loss: 900/1476 [=================>............] - ETA: 2s - loss: 153.4463 - kl_loss:1000/1476 [===================>..........] - ETA: 1s - loss: 144.5965 - kl_loss:1100/1476 [=====================>........] - ETA: 1s - loss: 135.8906 - kl_loss:1200/1476 [=======================>......] - ETA: 1s - loss: 127.5663 - kl_loss:1300/1476 [=========================>....] - ETA: 0s - loss: 120.2627 - kl_loss:1400/1476 [===========================>..] - ETA: 0s - loss: 113.8881 - kl_loss: 1.5820Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [76,64] vs. [100,64]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 235, in <module>
    validation_data=(data_val, data_val), callbacks=[checkpointer])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1657, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1213, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [76,64] vs. [100,64]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]

Caused by op 'training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs', defined at:
  File "test.py", line 235, in <module>
    validation_data=(data_val, data_val), callbacks=[checkpointer])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1634, in fit
    self._make_train_function()
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/optimizers.py", line 415, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python3.6/dist-packages/keras/optimizers.py", line 73, in get_gradients
    grads = K.gradients(loss, params)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2394, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 779, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 779, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py", line 874, in _AddGrad
    rx, ry = gen_array_ops.broadcast_gradient_args(sx, sy)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 674, in broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'lambda_1/add', defined at:
  File "test.py", line 138, in <module>
    z = Lambda(sampling, output_shape=(latent_dim,))([z_mean, z_log_var])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "test.py", line 134, in sampling
    return z_mean + K.exp(z_log_var / 2) * epsilon
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [76,64] vs. [100,64]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]
