### ISSUE TITLE
its very urgent

### ISSUE THREAD

**Issue by ghost** [NicGian/text-VAE#2]
BASE_DIR = 'C:/Users/gianc/Desktop/PhD/Progetti/vae/'
TRAIN_DATA_FILE = BASE_DIR + 'train.csv'#'train_micro.csv'
GLOVE_EMBEDDING = BASE_DIR + 'glove.6B.50d.txt'

can you pls attach train.csv and glove file

**Comment by ghost** [comment]
Train on 1476 samples, validate on 0 samples
Epoch 1/100
 100/1476 [=>............................] - ETA: 23s - loss: 179.8707 - kl_loss 200/1476 [===>..........................] - ETA: 12s - loss: 179.0795 - kl_loss 300/1476 [=====>........................] - ETA: 8s - loss: 178.2200 - kl_loss: 400/1476 [=======>......................] - ETA: 6s - loss: 177.2747 - kl_loss: 500/1476 [=========>....................] - ETA: 5s - loss: 175.7491 - kl_loss: 600/1476 [===========>..................] - ETA: 4s - loss: 172.9643 - kl_loss: 700/1476 [=============>................] - ETA: 3s - loss: 168.5350 - kl_loss: 800/1476 [===============>..............] - ETA: 3s - loss: 161.8723 - kl_loss: 900/1476 [=================>............] - ETA: 2s - loss: 153.4463 - kl_loss:1000/1476 [===================>..........] - ETA: 1s - loss: 144.5965 - kl_loss:1100/1476 [=====================>........] - ETA: 1s - loss: 135.8906 - kl_loss:1200/1476 [=======================>......] - ETA: 1s - loss: 127.5663 - kl_loss:1300/1476 [=========================>....] - ETA: 0s - loss: 120.2627 - kl_loss:1400/1476 [===========================>..] - ETA: 0s - loss: 113.8881 - kl_loss: 1.5820Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [76,64] vs. [100,64]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 235, in <module>
    validation_data=(data_val, data_val), callbacks=[checkpointer])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1657, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1213, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [76,64] vs. [100,64]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]

Caused by op 'training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs', defined at:
  File "test.py", line 235, in <module>
    validation_data=(data_val, data_val), callbacks=[checkpointer])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1634, in fit
    self._make_train_function()
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/optimizers.py", line 415, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python3.6/dist-packages/keras/optimizers.py", line 73, in get_gradients
    grads = K.gradients(loss, params)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2394, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 779, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 779, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py", line 874, in _AddGrad
    rx, ry = gen_array_ops.broadcast_gradient_args(sx, sy)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 674, in broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'lambda_1/add', defined at:
  File "test.py", line 138, in <module>
    z = Lambda(sampling, output_shape=(latent_dim,))([z_mean, z_log_var])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "test.py", line 134, in sampling
    return z_mean + K.exp(z_log_var / 2) * epsilon
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [76,64] vs. [100,64]
	 [[Node: training/Adam/gradients/lambda_1/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training/Adam/gradients/lambda_1/add_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/gradients/lambda_1/add_grad/Shape, training/Adam/gradients/lambda_1/add_grad/Shape_1)]]
