### ISSUE TITLE
where is the dataset

### ISSUE THREAD

**Issue by SeekPoint** [NicGian/text-VAE#6]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/__Gen__/text_VAE$ python vae_text_s2sloss_kl_weight_V18_github.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "vae_text_s2sloss_kl_weight_V18_github.py", line 38, in <module>
    with codecs.open(TRAIN_DATA_FILE, encoding='utf-8') as f:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'C:/Users/gianc/Desktop/PhD/Progetti/vae/train.csv'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/__Gen__/text_VAE

**Comment by annong** [comment]
Hello! How can I get the datasets?
